path: D:\Python\TomatoPest\dataset
train: train/images
val: valid/images
test: test/images
nc: 8
names:
- Beet Armyworm-3
- Cotton Bollworm-1
- Green Peach Aphid-2
- Melon Fruit Fly-7
- Silverleaf Whitefly-0
- Tobacco Cutworm-4
- Two-spotted Spider Mite-6
- Western Flower Thrips-5
roboflow:
  workspace: esocfall
  project: tomato_yolo-xmckl
  version: 4
  license: CC BY 4.0
  url: https://universe.roboflow.com/esocfall/tomato_yolo-xmckl/dataset/4
